linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  funlen:
    lines: 100
    statements: 50
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/gortc
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - sloppyReassign
      - hugeParam

issues:
  exclude-use-default: false
  exclude:
    - "isOptional is a pure function"
    - "should have a package comment, unless it's in another file for this package"
  exclude-rules:
    - text: "string `(Unknown|<nil>|UDP)`"
      linters: [goconst]

    - text: \(\*candidateParser\)
      linters: [gocyclo]

    - linters: [dupl]
      source: "gather\\S+CandidatesFor"

    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
        - unparam
        - funlen
        - gocyclo
        - gocognit

    # Ease some gocritic warnings on test files.
    - path: _test\.go
      text: "(unnamedResult|exitAfterDefer|unlambda)"
      linters: [gocritic]

    - path: ^cmd/
      linters: [gocyclo]
    - path: ^cmd/
      text: "(unnamedResult|exitAfterDefer)"
      linters: [gocritic]

    # RFC references
    - linters: [godot]
      source: "RFC \\d+"
    - linters: [godot]
      source: " #nosec"
    # Code comments
    - linters: [godot]
      source: "\\/\\/\\s+}"

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - scopelint
    - gochecknoinits
    - prealloc
    - gomnd
    - wsl
    - godox
    - testpackage
    - goerr113

run:
  skip-dirs:
    - e2e
    - fuzz
    - testdata
    - _testdata
    - api

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.15.x # use fixed version to not introduce new linters unexpectedly
  prepare:
    - echo "here I can run custom commands, but no preparation needed"
