# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

ignored = ["github.com/gortc/ic2/e2e/webrtc-chrome"]

[[constraint]]
  name = "github.com/gortc/stun"
  version = "1.18"

[[constraint]]
  name = "github.com/gortc/turn"
  version = "0.6"

[[constraint]]
  name = "github.com/gortc/sdp"
  version = "0.15"


[prune]
  go-tests = true
  unused-packages = true
